In [67]:
# Importación de librerías necesarias

import pandas as pd
import numpy as np

### Helados por sabor

La empresa _Ice Cream Avenue_ desea realizar un seguimiento de los sabores de helado más populares para un cliente. 
Se te proporciona una lista de pedidos, donde cada pedido es una lista con tuplas con el sabor del helado y la cantidad solicitada. 
* En el primer pedido se piden 3 helados de chocolate, 2 de vainilla y 4 de fresa
* En el segundo pedido se pide 1 helado de chocolate, 2 de yogur y 3 de fresa
* En el tercer pedido se piden 2 helados de yogur y 2 de mango

Concatena las listas, y escribe una función que, en base a esa lista total, genere un diccionario que muestre la cantidad total de helados pedidos para cada sabor.

In [68]:
# Lista de tuplas de los pedidos
pedido1 = [('chocolate', 3), ('vainilla', 2), ('fresa', 4)]
pedido2 = [('chocolate', 1), ('yogur', 2), ('fresa', 3)]
pedido3 = [('yogur', 2), ('mango', 2)]

# Suma tuplas en una misma lista y creación de un diccionario vacío
pedidos_totales = pedido1 + pedido2 + pedido3
sabores = {}

# Función que recibe una lista de tuplas de helados y genera un diccionario
# que calcula la cantidad total de helados separados por sabor
def contar_helados(pedidos_totales):
    for helado in pedidos_totales:
        sabor, cantidad= helado
        if sabor not in sabores:
            sabores[sabor] = cantidad
        else:
            sabores[sabor] += cantidad
    return sabores

# Llamada a la función que calcula el diccionario
total_helados = contar_helados(pedidos_totales)
print(f'El número total de helados es: {total_helados}')

El número total de helados es: {'chocolate': 4, 'vainilla': 2, 'fresa': 7, 'yogur': 4, 'mango': 2}


### Descuentos en helados 

Partiendo de los sabores del ejercicio anterior, generar una lista de precios, donde el precio de cada sabor sea 0.2€ por cada letra que contenga, y con un descuento del 20% para los helados cuyo nombre empiece con la letra "c".

In [69]:
# Lista de sabores de los helados
lista_sabores = ['chocolate', 'vainilla', 'fresa', 'yogur', 'mango']

# Función que recibe una lista de sabores y genera una lista de precios
def calcular_precio(sabor):
    precio_base = 0.2 * len(sabor)

    if sabor.startswith('c'):
        precio_base -= precio_base * 0.2
    return sabor, precio_base

# Llamada a la función que calcula los precios de cada sabor
precios = [calcular_precio(sabor) for sabor in lista_sabores]
print(precios)


[('chocolate', 1.44), ('vainilla', 1.6), ('fresa', 1.0), ('yogur', 1.0), ('mango', 1.0)]


### El helado más caro

A partir del diccionario del ejercicio anterior con precios de helados y un presupuesto dado, crea una función que devuelva el helado más caro cubierto por el presupuesto.

Resuélvelo primero con python base, y después utilizando Series de pandas

In [70]:
# 1. Python base

# Lista de precios y presupuesto
precio_helados = {'chocolate': 1.44, 'vainilla': 1.6, 'fresa': 1.0, 'yogur': 1.0, 'mango': 1.0}
presupuesto = 1.55

# Función que recibe un diccionario de precios y un presupuesto y devuelve
# el helado más caro cubierto por el presupuesto
def helado_caro(precio_helados, presupuesto):
    helado_mas_caro = max((precio, helado) for helado, precio in precio_helados.items() if precio <= presupuesto)
    return helado_mas_caro

#Llamada a la función que calcula el helado más caro cubierto por
# el presupuesto
precio, helado = helado_caro(precio_helados, presupuesto)
print('Python base:')
print(f'Helado más caro que puedo comprar es el del sabor {helado}, a un precio de: {precio}€\n')


# 2. Series de pandas

# Convertir el diccionario de precios a una serie de pandas
precios_series = pd.Series(precio_helados)

def helado_caro(precios_series, presupuesto):
    # Filtrar los helados cuyo precio sea menor o igual al presupuesto
    helados_disponibles = precios_series[precios_series <= presupuesto]
    
# Encontrar el helado más caro entre los disponibles
    helado_mas_caro = helados_disponibles.idxmax()
    precio_mas_caro = helados_disponibles.max()
    
    return helado_mas_caro, precio_mas_caro

helado, precio = helado_caro(precios_series, presupuesto)
print('Series de pandas:')
print(f'Helado más caro que puedo comprar es el del sabor {helado}, a un precio de: {precio}€')

Python base:
Helado más caro que puedo comprar es el del sabor chocolate, a un precio de: 1.44€

Series de pandas:
Helado más caro que puedo comprar es el del sabor chocolate, a un precio de: 1.44€


### Ventas aleatorias

Crea un array bidimensional en numpy donde la dimensión de filas sea el número de tiendas (5) y las columnas los días de la semana. Los datos deben obtenerse a partir de una distribución aleatoria de números enteros, que puede ir desde 0 hasta 100 (sin incluir). Asegúrate de que el ejemplo sea reproducible, fijando como semilla el número 42

In [71]:
# Fijar la semilla para que el ejemplo sea reproducible
np.random.seed(42)

# Array bidimensional de 5 filas (tiendas) y 7 columnas (días de la semana)
datos = np.random.randint(1, 99, size=(5, 7))

print("Array bidimensional de ventas:")
print(datos)


Array bidimensional de ventas:
[[52 93 15 72 61 21 83]
 [87 75 75 88 24  3 22]
 [53  2 88 30 38  2 64]
 [60 21 33 76 58 22 89]
 [49 91 59 42 92 60 80]]


### Llegando a 200 ventas

Calcula el dia de la semana en que cada tienda alcanza las 200 ventas acumuladas a lo largo de la semana

In [72]:
# Calcular la suma acumulativa a lo largo de los días de la semana para cada tienda
ventas_acumuladas = np.cumsum(datos, axis=1)

# Ahora el array quedaría así
print(ventas_acumuladas)

# Encontrar el primer día en el que se alcanzan o superan las 200 ventas acumuladas
dias_alcanzados = np.argmax(ventas_acumuladas >= 200, axis=1)

# argmax tiene en cuenta el primer día como 0, por ello, el día 3
# corresponde al jueves, el día 4 corresponde al viernes, etc.
print("\nDía de la semana en que cada tienda alcanza las 200 ventas acumuladas:")
print(dias_alcanzados)


[[ 52 145 160 232 293 314 397]
 [ 87 162 237 325 349 352 374]
 [ 53  55 143 173 211 213 277]
 [ 60  81 114 190 248 270 359]
 [ 49 140 199 241 333 393 473]]

Día de la semana en que cada tienda alcanza las 200 ventas acumuladas:
[3 2 4 4 3]


### Beneficio positivo

Crea otro array con la misma forma que el de ventas que se llame costes, y el valor constante 40. Resta ambos arrays para obtener un array que se llame beneficio, y calcula el beneficio sumado de las tiendas que tengan beneficio total positivo.

In [73]:
# Crear un array de costes con la misma forma que el array de ventas
costes = np.full_like(datos, 40)

# Calcular el array de beneficio restando los costes de las ventas
beneficio = datos - costes

# Encontrar las tiendas con beneficio total positivo
tiendas_con_beneficio_positivo = beneficio.sum(axis=1) > 0

# Calcular la suma de los beneficios de las tiendas con beneficio total positivo
beneficio_total_positivo = beneficio[tiendas_con_beneficio_positivo].sum()

print(f'Array con resultados, despúes de costes:\n{beneficio}\n')
print("Beneficio total de las tiendas con beneficio total positivo:", beneficio_total_positivo)

Array con resultados, despúes de costes:
[[ 12  53 -25  32  21 -19  43]
 [ 47  35  35  48 -16 -37 -18]
 [ 13 -38  48 -10  -2 -38  24]
 [ 20 -19  -7  36  18 -18  49]
 [  9  51  19   2  52  20  40]]

Beneficio total de las tiendas con beneficio total positivo: 483


### Lectura de fichero

Lee el fichero de ventas_por_helado y haz una exploración rápida del DataFrame

In [74]:
# Lee el archivo CSV
df = pd.read_csv('ventas_por_helado.csv')

# Muestra las primeras filas del DataFrame
print("Primeras filas del DataFrame:")
print(df.head())


Primeras filas del DataFrame:
   id_producto  ventas_unidades    precio
0           17           998119  1.493301
1          101            27127  3.848544
2          240           202538  2.406505
3          402           266723  2.989612
4          999            20468  1.859808


In [75]:
# Muestra información básica del DataFrame
print("\nInformación del DataFrame:")
print(df.info())


Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id_producto      16 non-null     int64  
 1   ventas_unidades  16 non-null     int64  
 2   precio           16 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 516.0 bytes
None


In [76]:
# Muestra estadísticas descriptivas del DataFrame
print("\nEstadísticas descriptivas del DataFrame:")
print(df.describe())


Estadísticas descriptivas del DataFrame:
       id_producto  ventas_unidades     precio
count    16.000000         16.00000  16.000000
mean   3962.500000     240504.25000   2.899529
std    3061.347634     304497.61091   1.031506
min      17.000000       4051.00000   1.493301
25%     849.750000      25462.25000   2.392031
50%    4522.500000      96458.50000   2.528107
75%    5894.250000     312294.00000   3.171675
max    9134.000000     998119.00000   5.158462


In [77]:
# Muestra los nombres de las columnas del DataFrame
print("\nNombres de las columnas del DataFrame:")
print(df.columns)


Nombres de las columnas del DataFrame:
Index(['id_producto', 'ventas_unidades', 'precio'], dtype='object')


In [78]:
# Muestra la cantidad de filas y columnas del DataFrame
print("\nCantidad de filas y columnas del DataFrame:")
print(df.shape)


Cantidad de filas y columnas del DataFrame:
(16, 3)


### Productos con mucha venta

Calcula el número de productos con más de 20000 euros en ventas

In [101]:
# Selecciona las filas donde las ventas son mayores que 20000 euros
productos_mas_20000 = df[df['ventas_unidades'] > 20000]

# Calcula el número de productos con más de 20000 euros en ventas
numero_productos_mas_20000 = productos_mas_20000.shape[0]


print(f'Este sería el total de productos con más de 20000 euros en ventas:\n{productos_mas_20000}\n')
print("Número total de productos con más de 20000 euros en ventas:", numero_productos_mas_20000)

Este sería el total de productos con más de 20000 euros en ventas:
    id_producto  ventas_unidades    precio
0            17           998119  1.493301
1           101            27127  3.848544
2           240           202538  2.406505
3           402           266723  2.989612
4           999            20468  1.859808
5          2033           209155  2.489806
6          3636            32070  2.601165
8          4577           130704  5.158462
9          4758           449007  5.031154
11         5684            45269  3.717864
12         6525            62213  2.357885
14         8689           689257  2.552039
15         9134           679493  2.391456

Número total de productos con más de 20000 euros en ventas: 13
